name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    # Obtendo os 7 primeiros caracteres da hash do commit 
    # para gerar a versão da imagem
    # utiliza-se o $GITHUB_OUTPUT para obter a saída do comando
    # permitindo assim a utilização desse valor no próximo step
    - name: Generate SHA
      id: generate_sha
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT
    
    # Login no container registry
    # Por padrão a configuração já é referente ao docker hub
    - name: Login into the container registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true # por padrão é feito apenas o build 
        tags: | 
          lipeeeeh14/nlw-journey-devops:${{ steps.generate_sha.outputs.sha }}
          lipeeeeh14/nlw-journey-devops:latest